name: importNewStrings 
on: workflow_dispatch 
# We can switch to scheudle later
#    schedule:
#        - cron:  '*/15 * * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
        image: alpine
    steps:
      - run: apk update && apk add qt5-qttools-dev git
      - uses: actions/checkout@v2
      - run: npm install -g bats
      - run: bats -v
