name: importNewStrings 
on: workflow_dispatch 
# We can switch to scheudle later
#    schedule:
#        - cron:  '*/15 * * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
        image: alpine
    steps:
      - run: apk update && apk add qt5-qttools-dev git
      - uses: actions/checkout@v2
        with:
          path: "translationFiles"
      - uses: actions/checkout@v2
        with:
          repository: "bakulf/mv"
          path: "vpn"
          token: ${{ secrets.ACCESSCODE }}
      - run: ls -l 
      - run: /usr/lib/qt5/bin/lupdate vpn/src/src.pro -ts
      - run: for filename in vpn/translations/*; do /usr/lib/qt5/bin/lconvert -i filename -o translationFiles/${$filename%%.*}.xlf; done;
      - run: ls -l /translationFiles/