name: importNewStrings 
on: push 
# We can switch to scheudle later
#    schedule:
#        - cron:  '*/15 * * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
        image: alpine
    steps:
      - run: apk update && apk add qt5-qttools-dev git bash
      - uses: actions/checkout@v2
        with:
          path: "translationFiles"
      - uses: actions/checkout@v2
        with:
          repository: "bakulf/mv"
          path: "vpn"
          token: ${{ secrets.ACCESSCODE }}
      - run: ls -l 
      - run: chmod +x translationFiles/import.sh && bash translationFiles/import.sh
      - run: ls -l /translationFiles/