name: importNewStrings 
on: push 
# We can switch to scheudle later
#    schedule:
#        - cron:  '*/15 * * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
        image: debian
    steps:
      - run: apt update && apt install qttools5-dev-tools qt5-default g++ make -y
      - uses: actions/checkout@v2
        with:
          path: "translationFiles"
      - uses: actions/checkout@v2
        with:
          repository: "bakulf/mv"
          path: "vpn"
          token: ${{ secrets.ACCESSCODE }}
      - run: ls -l 
      - run: chmod +x translationFiles/import.sh && bash translationFiles/import.sh
      - run: ls -l translationFiles/