name: importNewStrings 
on: push 
# We can switch to scheudle later
#    schedule:
#        - cron:  '*/15 * * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
        image: debian
    steps:
      - run: apt update && apt install qttools5-dev-tools qt5-default g++ make git -y
      - uses: actions/checkout@v2
        with:
          path: "translationFiles"
      - uses: actions/checkout@v2
        with:
          repository: "bakulf/mv"
          path: "vpn"
          token: ${{ secrets.ACCESSCODE }}
      - run: ls -l 
      - run: chmod +x translationFiles/.github/import.sh && bash translationFiles/.github/import.sh
      - run: ls -l translationFiles/
      - run : git config user.email 'strseb@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v3
        with: 
          path: "translationFiles"
          commit-message: "Auto Commit new Language Strings"
          branch-suffix: "timestamp"
          title: "Import new Language Files"