name: L10n Linter
on:
  schedule:
    - cron: '0 7 * * 1-5' # Run Mon-Fri at 7AM UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r .github/scripts/requirements.txt
      - name: Check strings
        run: |
          python translationFiles/.github/scripts/check_locales.py --xliff mozillavpn.xliff --path .
