name: L10n Linter
on:
  schedule:
    - cron: "0 7 * * 1-5" # Run Mon-Fri at 7AM UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          pip install -r .github/scripts/requirements.txt
      - name: Check strings
        run: |
          python .github/scripts/xliff_l10n.py --l10n . --exceptions .github/scripts/exceptions.json
