name: Update Strings
on:
  schedule:
    - cron: '0 7 * * 1-5' # Run Mon-Fri at 7AM UTC
  workflow_dispatch:
    inputs:
      type:
        description: Type of update (standard, nofile, matchid)
        required: true
        default: "standard"
jobs:
  extract:
    name: Extract strings
    runs-on: ubuntu-latest
    env:
      QTVERSION: 6.2.4
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v3
        with:
          path: "translationFiles"
      - name: Install Qt
        run: |
          python3 -m pip install aqtinstall
          python3 -m aqt install-qt -O /opt linux desktop $QTVERSION
      - name: Clone main code repository
        uses: actions/checkout@v3
        with:
          repository: "mozilla-mobile/mozilla-vpn-client"
          fetch-depth: 0
          path: "vpn"
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install -r translationFiles/.github/scripts/requirements.txt
      - name: Extract new strings
        run: |
          # Manually add QT executables to path
          export PATH=/opt/$QTVERSION/gcc_64/bin:$PATH

          # Extract strings for default and release branches
          (cd vpn && ./scripts/utils/generate_ts.sh)
          mv vpn/translations.ts .

          # Convert main strings to XLIFF
          python translationFiles/.github/scripts/extract_source_strings.py --input translations.ts --output translationFiles/en/mozillavpn.xliff

          # Convert addon strings to XLIFF
          if [ -d "vpn/addon_ts" ]; then
            addon_files="vpn/addon_ts/*.ts"
            for f in $addon_files
            do
              addon_name=$(basename "$f" .ts)
              echo "Extracting strings for addon: ${addon_name}.ts"
              mkdir -p "translationFiles/en/addons/${addon_name}"
              python translationFiles/.github/scripts/extract_source_strings.py --input "vpn/addon_ts/${addon_name}.ts" --output "translationFiles/en/addons/${addon_name}/strings.xliff"
            done
          fi

          # Update other locales
          python translationFiles/.github/scripts/update_other_locales.py --reference en --path translationFiles/ --type "${{ github.event.inputs.type }}"
      - run : git config --global user.email 'flodolo@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v4
        with:
          path: "translationFiles"
          commit-message: "Extract new strings and update all locales"
          branch: l10n_automation
          delete-branch: true
          title: "Extract new strings"
