name: UpdateStrings
on:
  schedule:
    - cron: '0 7 * * 1-5' # Run Mon-Fri at 7AM UTC
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Linux packages
        run: |
          # Add external PPA, latest version of QT is 5.12.x for Ubuntu 20.04
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.0-focal -y
          sudo apt update
          sudo apt install git qt515tools -y
      - name: Clone l10n repository
        uses: actions/checkout@v2
        with:
          path: "translationFiles"
      - name: Clone main code repository
        uses: actions/checkout@v2
        with:
          repository: "mozilla-mobile/mozilla-vpn-client"
          path: "vpn"
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r translationFiles/.github/requirements.txt
      - name: Extract new strings
        run: |
          # Manually add QT executables to path
          export PATH=/opt/qt515/bin:$PATH
          lupdate -version
          python translationFiles/.github/extract_source_strings.py
          python translationFiles/.github/update_other_locales.py --reference en --xliff mozillavpn.xliff --path translationFiles/
      - run : git config --global user.email 'flodolo@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v3
        with:
          path: "translationFiles"
          commit-message: "Extract new strings and update all locales"
          branch: l10n_automation
          delete-branch: true
          title: "Extract new strings"
