name: UpdateStrings
on:
  schedule:
    - cron: '0 12 * * 1' #  At 12:00 on every Monday
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
        image: debian
    steps:
      - run: apt update && apt install python3 qttools5-dev-tools qt5-default g++ make git -y
      - uses: actions/checkout@v2
        with:
          path: "translationFiles"
      - uses: actions/checkout@v2
        with:
          repository: "mozilla-mobile/mozilla-vpn-client"
          path: "vpn"
          token: ${{ secrets.ACCESSCODE }}
      - run: ls -l
      - run: python3 translationFiles/.github/update.py
      - run: ls -l translationFiles/
      - run: qmake -v
      - run : git config --global user.email 'strseb@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v3
        with:
          path: "translationFiles"
          commit-message: "Auto Commit new Strings"
          branch-suffix: "timestamp"
          title: "Import new Strings"
