name: UpdateStrings
on:
  schedule:
    - cron: '0 12 * * 1' #  At 12:00 on every Monday
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install qttools5-dev-tools qt5-default g++ make git -y
      - name: Clone l10n repository
        uses: actions/checkout@v2
        with:
          path: "translationFiles"
      - name: Clone main code repository
        uses: actions/checkout@v2
        with:
          repository: "mozilla-mobile/mozilla-vpn-client"
          path: "vpn"
          token: ${{ secrets.ACCESSCODE }}
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r translationFiles/.github/requirements.txt
      - name: Extract new strings
        run: |
          qmake -v
          python translationFiles/.github/extract_source_strings.py
          python translationFiles/.github/update_other_locales.py --reference en --xliff mozillavpn.xliff --path translationFiles/
      - run : git config --global user.email 'strseb@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v3
        with:
          path: "translationFiles"
          commit-message: "Extract new strings and update all locales"
          branch-suffix: "timestamp"
          title: "Extract new strings"
